import { defineStore } from 'pinia'
import { ref } from 'vue'
import type { CardSource } from '../types/index.ts'

// Loads the card provenance table (public/data/card-sources.json, generated by
// `npm run card-sources`) for the Reference → Card Sources section (Feature 18).
export const useCardSourcesStore = defineStore('cardSources', () => {
  const sources = ref<CardSource[]>([])
  const loaded = ref(false)

  async function load() {
    if (loaded.value) return
    try {
      const res = await fetch('/data/card-sources.json')
      if (res.ok) sources.value = await res.json()
    } catch {
      // reference-only data; absence just shows an empty table
    }
    loaded.value = true
  }

  return { sources, loaded, load }
})
