// generate-card-origins — (re)build card_list_origin.md, the provenance record.
//
// Card images are git-ignored, so this markdown is the durable audit trail of where
// each card scan came from. For every catalogue card it records the source:
//   - "AMG <PDF>"      — re-sourced from an official PnP PDF (read from amg-card-map.json)
//   - "AMG DOC56 (self)"— self-sourced Mandalorian errata (PRESERVE_SLUGS)
//   - "LHQ2"           — still the legacy Legion HQ 2 scan (to be expunged before 2.0)
//
// Run with: npm run amg:origins   (regenerate after every apply batch)

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { isPreserved, pdfBasename } from '../scraper/amgNormalise.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const DATA = join(ROOT, 'public', 'data')
const MAP_PATH = join(ROOT, 'scraper', 'amg-card-map.json')

interface Card { slug: string; name: string; title?: string | null }
type Cat = 'units' | 'upgrades' | 'commands' | 'battle'
const FILES: Record<Cat, string> = {
  units: 'units.json', upgrades: 'upgrades.json', commands: 'commands.json', battle: 'battleCards.json',
}

function load(file: string): Card[] {
  return JSON.parse(readFileSync(join(DATA, file), 'utf8'))
}

interface MapEntry { category: Cat; slug: string; sourcePdf: string }
const map: MapEntry[] = existsSync(MAP_PATH) ? JSON.parse(readFileSync(MAP_PATH, 'utf8')) : []
const sourceBySlug = new Map(map.map((e) => [`${e.category}:${e.slug}`, pdfBasename(e.sourcePdf)]))

function origin(cat: Cat, slug: string): string {
  if (isPreserved(cat, slug)) return 'AMG DOC56 (self)'
  const pdf = sourceBySlug.get(`${cat}:${slug}`)
  return pdf ? `AMG ${pdf}` : 'LHQ2'
}

const lines: string[] = []
lines.push('# Card image provenance (`card_list_origin.md`)')
lines.push('')
lines.push('Generated by `npm run amg:origins`. Card scans are git-ignored, so this file is the')
lines.push('durable record of where each card image was sourced. The 2.0 goal is **0 LHQ2 rows**:')
lines.push('every card re-sourced from an official AMG print-and-play PDF (or already self-sourced).')
lines.push('')

const totals = { 'AMG': 0, 'AMG DOC56 (self)': 0, LHQ2: 0 }
const sections: string[] = []
for (const cat of Object.keys(FILES) as Cat[]) {
  const cards = load(FILES[cat]).sort((a, b) => a.slug.localeCompare(b.slug))
  const rows: string[] = []
  let amg = 0, self = 0, lhq = 0
  for (const c of cards) {
    const o = origin(cat, c.slug)
    if (o === 'LHQ2') lhq++
    else if (o === 'AMG DOC56 (self)') self++
    else amg++
    rows.push(`| \`${c.slug}\` | ${c.name}${c.title ? ` — ${c.title}` : ''} | ${o} |`)
  }
  totals.AMG += amg; totals['AMG DOC56 (self)'] += self; totals.LHQ2 += lhq
  sections.push(`## ${cat} (${cards.length}) — AMG ${amg + self} / LHQ2 ${lhq}\n`)
  sections.push('| slug | card | source |')
  sections.push('|---|---|---|')
  sections.push(...rows)
  sections.push('')
}

const totalAll = totals.AMG + totals['AMG DOC56 (self)'] + totals.LHQ2
lines.push('## Summary')
lines.push('')
lines.push('| source | count |')
lines.push('|---|---|')
lines.push(`| AMG PnP (re-sourced) | ${totals.AMG} |`)
lines.push(`| AMG DOC56 (self-sourced) | ${totals['AMG DOC56 (self)']} |`)
lines.push(`| **Legion HQ 2 (to expunge)** | **${totals.LHQ2}** |`)
lines.push(`| total | ${totalAll} |`)
lines.push('')
lines.push(...sections)

writeFileSync(join(ROOT, 'card_list_origin.md'), lines.join('\n'))
console.log(`Wrote card_list_origin.md — AMG ${totals.AMG + totals['AMG DOC56 (self)']}, LHQ2 ${totals.LHQ2}, total ${totalAll}.`)
