// generate-card-origins — (re)build card_list_origin.md, the provenance record.
//
// Card images are git-ignored, so this markdown is the durable audit trail of where
// each card scan came from. For every catalogue card it records the source:
//   - "AMG <PDF>"      — re-sourced from an official PnP PDF (read from amg-card-map.json)
//   - "AMG DOC56 (self)"— self-sourced Mandalorian errata (PRESERVE_SLUGS)
//   - "LHQ2"           — still the legacy Legion HQ 2 scan (to be expunged before 2.0)
//
// Run with: npm run amg:origins   (regenerate after every apply batch)

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { isPreserved, pdfBasename } from '../scraper/amgNormalise.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const DATA = join(ROOT, 'public', 'data')
const MAP_PATH = join(ROOT, 'scraper', 'amg-card-map.json')

interface Card { slug: string; name: string; title?: string | null }
type Cat = 'units' | 'upgrades' | 'commands' | 'battle'
const FILES: Record<Cat, string> = {
  units: 'units.json', upgrades: 'upgrades.json', commands: 'commands.json', battle: 'battleCards.json',
}

function load(file: string): Card[] {
  return JSON.parse(readFileSync(join(DATA, file), 'utf8'))
}

interface MapEntry { category: Cat; slug: string; sourcePdf: string }
const map: MapEntry[] = existsSync(MAP_PATH) ? JSON.parse(readFileSync(MAP_PATH, 'utf8')) : []
const sourceBySlug = new Map(map.map((e) => [`${e.category}:${e.slug}`, pdfBasename(e.sourcePdf)]))

// Cards intentionally WITHOUT an image (unreleased.json `noImage: true`): their legacy
// scan is expunged and the app shows the branded "image pending" placeholder. These are
// NOT LHQ2 rows — they have no image dependency on any external source at all.
const noImageSlugs = new Set<string>((() => {
  try {
    const u = JSON.parse(readFileSync(join(DATA, 'unreleased.json'), 'utf8'))
    const out: string[] = []
    for (const cat of ['units', 'commands', 'upgrades'] as Cat[]) {
      for (const [slug, e] of Object.entries(u[cat] ?? {})) {
        if (e && typeof e === 'object' && (e as { noImage?: boolean }).noImage) out.push(`${cat}:${slug}`)
      }
    }
    return out
  } catch { return [] }
})())

// Cards DROPPED ENTIRELY from the app (public/data/dropped.json): first-edition (v1)
// cards with no current-edition equivalent. Filtered out of the stores at load, so they
// are NOT LHQ2 rows for the 2.0 "0 LHQ2" goal — they leave the app rather than getting an
// image.
const droppedSlugs = new Set<string>((() => {
  try {
    const d = JSON.parse(readFileSync(join(DATA, 'dropped.json'), 'utf8'))
    const out: string[] = []
    for (const cat of ['units', 'commands', 'upgrades'] as Cat[]) {
      for (const slug of (d[cat] ?? []) as string[]) out.push(`${cat}:${slug}`)
    }
    return out
  } catch { return [] }
})())

function origin(cat: Cat, slug: string): string {
  if (droppedSlugs.has(`${cat}:${slug}`)) return 'dropped (v1 — removed)'
  if (noImageSlugs.has(`${cat}:${slug}`)) return 'none (no source)'
  if (isPreserved(cat, slug)) return 'AMG DOC56 (self)'
  const pdf = sourceBySlug.get(`${cat}:${slug}`)
  return pdf ? `AMG ${pdf}` : 'LHQ2'
}

const lines: string[] = []
lines.push('# Card image provenance (`card_list_origin.md`)')
lines.push('')
lines.push('Generated by `npm run amg:origins`. Card scans are git-ignored, so this file is the')
lines.push('durable record of where each card image was sourced. The 2.0 goal is **0 LHQ2 rows**:')
lines.push('every card re-sourced from an official AMG print-and-play PDF (or already self-sourced).')
lines.push('')

const totals = { 'AMG': 0, 'AMG DOC56 (self)': 0, LHQ2: 0, none: 0, dropped: 0 }
const sections: string[] = []
for (const cat of Object.keys(FILES) as Cat[]) {
  const cards = load(FILES[cat]).sort((a, b) => a.slug.localeCompare(b.slug))
  const rows: string[] = []
  let amg = 0, self = 0, lhq = 0, none = 0, dropped = 0
  for (const c of cards) {
    const o = origin(cat, c.slug)
    if (o === 'LHQ2') lhq++
    else if (o === 'none (no source)') none++
    else if (o === 'dropped (v1 — removed)') dropped++
    else if (o === 'AMG DOC56 (self)') self++
    else amg++
    rows.push(`| \`${c.slug}\` | ${c.name}${c.title ? ` — ${c.title}` : ''} | ${o} |`)
  }
  totals.AMG += amg; totals['AMG DOC56 (self)'] += self; totals.LHQ2 += lhq; totals.none += none; totals.dropped += dropped
  sections.push(`## ${cat} (${cards.length}) — AMG ${amg + self} / LHQ2 ${lhq}${none ? ` / none ${none}` : ''}${dropped ? ` / dropped ${dropped}` : ''}\n`)
  sections.push('| slug | card | source |')
  sections.push('|---|---|---|')
  sections.push(...rows)
  sections.push('')
}

const totalAll = totals.AMG + totals['AMG DOC56 (self)'] + totals.LHQ2 + totals.none + totals.dropped
lines.push('## Summary')
lines.push('')
lines.push('| source | count |')
lines.push('|---|---|')
lines.push(`| AMG PnP (re-sourced) | ${totals.AMG} |`)
lines.push(`| AMG DOC56 (self-sourced) | ${totals['AMG DOC56 (self)']} |`)
lines.push(`| none (no source — placeholder) | ${totals.none} |`)
lines.push(`| dropped (v1 — removed from app) | ${totals.dropped} |`)
lines.push(`| **Legion HQ 2 (to expunge)** | **${totals.LHQ2}** |`)
lines.push(`| total | ${totalAll} |`)
lines.push('')
lines.push(...sections)

writeFileSync(join(ROOT, 'card_list_origin.md'), lines.join('\n'))
console.log(`Wrote card_list_origin.md — AMG ${totals.AMG + totals['AMG DOC56 (self)']}, none ${totals.none}, dropped ${totals.dropped}, LHQ2 ${totals.LHQ2}, total ${totalAll}.`)
